server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway-server
  zipkin:
    baseUrl: http://localhost:9411/
  cloud:    
    gateway:      
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-catalog
          uri: lb://api-catalog
          predicates:
            - Path=/api/v1/catalog/**
        - id: api-movie
          uri: lb://api-movie
          predicates:
            - Path=/api/v1/movies/**

info:
  app:
    name: ${spring.application.name}

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8789/eureka
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway